name: backend-ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v4
        # Set up a python environment using the specified python version.
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
      # Install the dependencies.
      - run: pip install pipenv
      - run: pipenv install
      - run: pip install flake8
      # Run the linter.
      - run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v4
      # Set up a python environment using the specified python version.
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      # Install the dependencies.
      - run: pip install pipenv
      - run: pipenv install
      # Run the test.
      - run: pipenv run pytest

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v4
      # Set up a python environment using the specified python version.
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Build Docker Image
        run: |
          docker build -t pj4-be .
